css/main.scss

Add top margin on Contact->Map on mobile

---

_sass/navigation.scss
css/main.scss

- Use mobile nav on tablet as well
- Adjust logo size on to be large on desktop, smaller on tablet/mobile
- Align hamburger icon

Responsive Nav updates

---

_includes/footer.html
_includes/header.html
_includes/nav_links.html
_sass/navigation.scss

- Removes reliance on javascript to display drop-downs, making touch screen behavior smoother
- Adds an IntersectionObserver to change mobile nav bgcolor on scroll
- Color can be changed in `navigation.scss > line 24`

Mobile Nav improvements

---

_includes/head.html

favicon was not appearing on sub pages

Fix favicon url 

---

_includes/head.html

Updated twitter card image

---

_includes/article_index.html

hot-fix for blog title length

---

_posts/2020-03-25-remote-work
_posts/2020-03-25-remote-work.md

This is the final copy for the telework blog. This blog should be published on 3/25/2020
NOTE: There are a number of images that are set to publish with this blog that also needs accompanying pushes to be approved. See the list below.
1. #68 bg Image for Telework Blog
2. #79 - feat Image for Telework Blog
3. #70 - create Folder for Single Images
3a. Once #70 has been resolved I'll need to upload [this image][(https://gorafttech-my.sharepoint.com/:i:/g/personal/rhunter_goraft_tech/EVEmynaU2GNCof0XVCLfbuUBhLT0svZAj5PNriTLBlGrDw?e=bpbrFE) to the assets/images/SingleImages/ directory

Publish Telework Blog

---

_posts/2020-03-10-ui-design-trends.md
_posts/2020-03-25-remote-work.md

Change the image on the remote work page and add short titles

change remote image

---

_posts/2020-03-25-remote-work.md
css/main.scss

Before:
- Image appears horizontally distorted on mobile
- Text squished on tablet
After:
- Image aspect ratio correct on all
- Text not squished

Remote Work Post - Make floated image responsive

---

_posts/2020-04-01-repo_documentation.md

This is the final copy for the documentation blog. This blog should be published on 4/1/2020
NOTE: There are a number of images that are set to publish with this blog that also needs accompanying pushes to be approved. See the list below. 
1. #74 - bg Image for Documentation Blog
2. #75 - feat Image for Documentation Blog
3. #70 - create Folder for Single Images
3a. Once #70 has been resolved I'll need to upload [this image](https://gorafttech-my.sharepoint.com/:i:/g/personal/rhunter_goraft_tech/EdlOdKwVJqZJkQ2dV-yQu0sB3cmAKZT38dIMueSia_Xk_g?e=KHRioa) to the assets/images/SingleImages/ directory

Publish Documentation Blog

---

_layouts/post.html
_posts/2018-10-12-a-gentle-intorduction-to-feed-forward-neural-networks.md
_posts/2018-12-02-using-convolutional-neural-networks-to-model-spatially-related-data.md
_posts/2019-01-04-dimensionality-reduction.md
_posts/2019-02-15-a-gentle-introduction-to-high-performance-computing.md
_posts/2019-05-02-getting-to-know-the-python-packages-that-help-you-do-machine-learning.md
_posts/2019-05-28-human-centered-design.md
_posts/2020-02-19-engineering-principles.md

- Add authors to unattributed posts
- Display author's first name only

Add missing blog post authors

---

_includes/head.html

Will added a [robot meta tag](https://developers.google.com/search/reference/robots_meta_tag) for any page/post via Front Matter. Closes #54

added robot tag to <head>

---

_posts/2020-04-08-the-benefits-of-ux-design.md

I have formatted and reviewed Ryan's post for 04/08/2020

added post for 04/08/2020

---

.gitignore
Gemfile
_data/README.md
_data/members.yml
_layouts/about/profile.html

Add pagemaster plugin

---

_posts/2020-04-23-5-lessons-steve-jobs-can-teach-you-about-proposal-management.md

edited Christine's post for publishing.

add post for 04/23/2020

---

_posts/2020-04-23-5-lessons-steve-jobs-can-teach-you-about-proposal-management.md

I changed the short_title on this per Ryan's request.

edited short_title

---

Gemfile.lock
_includes/head.html
_layouts/post.html
_sass/_layout.scss
_sass/base/_variables.scss
css/main.scss

Change font size, font type, typography.

Improve typography

---

_includes/footer.html
_sass/navigation.scss

Sticky nav on desktop

---

Gemfile
Gemfile.lock
_config.yml
css/main.scss

- open hyperlinks in new tabs
- make hyperlinks look better

improve hyperlinks

---

_includes/head.html
_sass/base/_variables.scss
_sass/navigation.scss
css/main.scss

Make fonts standard across all parts of the site. Including navigation bar and font in cards. This is currently deployed on staging.

standardize font

---

404.html
_sass/404.scss
assets/404-animated-rings.svg
css/main.scss

Custom 404 page

---

_includes/data/about_experince.html
_includes/data/about_why_go_raft.html
_includes/data/join_interview_process.html
_layouts/contact.html
services-cloud-native.md
services-data-science.md
services-devsecops.md
services-product-strategy.md
work.md

Addresses or verifies 46/52 items in #157

Site Corrections

---

_about/adam_caron.md
_data/members.yml

Changing Full Stack to Fullstack

Standardizing Roles

---

_includes/data/join_fun.html
css/main.scss

Add link to job posting

---

_posts/2020-8-17-continue-exploring-hil.md

Proposed spelling and minor wording updates.

minor text changes

---

_posts/2020-09-07-Renewing-Certs-With-Zero-Downtime-on-K8s.md

Fixed minor typos and related issues

minor text issues

---

_data/members.yml

add the image to the members.yml

add image to yml

---

_data/members.yml
_layouts/about.html
_sass/_team.scss

made edits to *about.html* to sort the members with sketches to the top of the page.
- no new errors on the console
- looks visually correct

[dev]sorted pics to the top

---

_includes/article_index.html
_layouts/post.html
_posts/2020-11-02-agile-software-acquisition-continuous-relevance-dod.md

Include author last name for individual posts, increase index page short title length to use full second line.

post layout updates

---

_about/aaron_beavers.md
_about/dmitri_knapp.md
_data/members.yml

Contributes to Issue #192
- _about/aaron_beavers.md
- _about/dmitri_knapp.md
- _data/members.yml

added aaron and dmitri to about files

---

_about/nick_grippin.md
_about/ryan_salcido.md
_data/members.yml

added Ryan and Nick

---

_about/le_chen.md
_data/members.yml

Bio has been added.  I will add Github and LinkedIn when I get them so I am not closing the Issue.

added Le Chen bio

---

_posts/2021-2-24-diversity-is-our-superpower.md

I don't want to talk about it.

fixing missed updates

---

_includes/footer.html

add Boston office to footer

---

_includes/footer.html
_layouts/contact.html

Update new address

---

_includes/footer.html

Updates location map on contact page

update custom map name

---

_leadership/danielle_mccoy.md

Addresses https://github.com/raft-tech/raft-tech.github.io/issues/466

15yrs -> 10yrs for Danielle McCoy

---

_posts/2023-08-15-DevSecOps-Part-1.md

Fixes image path

---

_leadership/jessica_weaver.md

Updating Jess Weaver's position

---

_includes/dark-mode-toggle.html
_includes/footer.html
_includes/header.html
_includes/nav.html
js/search.js

Rs 494 remove light theme

---

_includes/wave-footer.html
_sass/_homepage.scss
_sass/_light-mode.scss
_sass/_mediaqueries.scss
index.html

Homepage updates

---

_includes/footer.html

Updates Raft's office address to our new HQ.

Updates office address

---

_config.yml
_includes/google-analytics.html
_layouts/default.html

Updates GA tag and ID. Also removes duplicate includes (google-analytics.html was being included both via scripts.html and directly in default.html).

Updates Analytics

---

_posts/2024-07-26-c2-in-the-age-of-ai.md

Fixes C2 in the Age of AI feature image extension
